vitrine_client:
    resource: "@VitrineBundle/Resources/config/routing/client.yml"
    prefix:   /client

vitrine_commande:
    resource: "@VitrineBundle/Resources/config/routing/commande.yml"
    prefix:   /commande

vitrine_admin_article:
        resource: "@VitrineBundle/Resources/config/routing/article.yml"
        prefix:   /admin/article

vitrine_homepage:
    path: /accueil
    defaults: { _controller: VitrineBundle:Default:index, name:Visiteur }

mentions:
    path: /mentions
    defaults: { _controller: VitrineBundle:Default:mentions }

hello:
    path: /hello/{visiteur}
    defaults: { _controller: VitrineBundle:Default:hello }

catalogue:
    path: /catalogue/
    defaults: { _controller: VitrineBundle:Default:catalogue }

articleByCat:
    path: /catalogue/{idCategorie}
    defaults: { _controller: VitrineBundle:Default:articleByCat }

contenuPanier:
    path: /panier/
    defaults: { _controller: VitrineBundle:Panier:showPanier }

ajouterPanier:
    path: /panier/ajouter/{id}
    defaults: { _controller: VitrineBundle:Panier:ajouterPanier }

supprimerPanier:
    path: /panier/supprimer/{id}
    defaults: { _controller: VitrineBundle:Panier:supprimerPanier }

viderPanier:
    path: /panier/vider
    defaults: { _controller: VitrineBundle:Panier:viderPanier}

connexion:
    path: /connexion
    defaults: { _controller: VitrineBundle:Client:connexion }
    methods:  [GET, POST]

passerCommande:
    path: /commande/passerCommande
    defaults: { _controller: VitrineBundle:Commande:passerCommande }

commandes:
    path: /commandes
    defaults: { _controller: VitrineBundle:Commande:showCommandes }