vitrine_homepage:
    path:     /accueil/{visiteur}
    defaults: { _controller: VitrineBundle:Default:index, name:Visiteur }

mentions:
    path: /mentions
    defaults: { _controller: VitrineBundle:Default:mentions }

hello:
    path: /hello/{visiteur}
    defaults: { _controller: VitrineBundle:Default:hello }

catalogue:
    path: /catalogue/
    defaults: { _controller: VitrineBundle:Default:catalogue }

articleByCat:
    path: /catalogue/{idCategorie}
    defaults: { _controller: VitrineBundle:Default:articleByCat }

contenuPanier:
    path: /panier/
    defaults: { _controller: VitrineBundle:Panier:showPanier }

ajouterPanier:
    path: /panier/ajouter/{id}
    defaults: { _controller: VitrineBundle:Panier:ajouterPanier }