vitrine:
    resource: "@VitrineBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_vitrine:
    resource: "@VitrineBundle/Resources/config/routing.yml"

login:
    pattern: /login
    defaults: { _controller: VitrineBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout