# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        VitrineBundle\ENtity\Client:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_CLIENT: ROLE_USER
        ROLE_ADMIN: ROLE_USER, ROLE_CLIENT

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        utilisateurs:
            entity: { class: VitrineBundle:Client, property: mail }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        vitrine_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /accueil

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/client/edit, role: ROLE_ADMIN }
        - { path: ^/commande, role: ROLE_USER }
