<?php

namespace VitrineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function articleLesPlusVendus() {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb->select('a')
            ->from('VitrineBundle:Article', 'a')
            ->orderBy('a.nbVentes', 'DESC')
            ->setMaxResults(3);
        $query = $qb->getQuery();
        return $query->getResult();
    }


}
