<?php

namespace VitrineBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListeSouhaitsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeSouhaitsRepository extends EntityRepository
{
}
