admin_article_index:
    path:     /admin
    defaults: { _controller: "VitrineBundle:Article:index" }
    methods:  GET

admin_article_new:
    path:     /new/admin
    defaults: { _controller: "VitrineBundle:Article:new" }
    methods:  [GET, POST]

admin_article_edit:
    path:     /{id}/edit/admin
    defaults: { _controller: "VitrineBundle:Article:edit" }
    methods:  [GET, POST]

admin_article_delete:
    path:     /{id}/delete/admin
    defaults: { _controller: "VitrineBundle:Article:delete" }
    methods:  DELETE

article_show:
    path:     /{id}/show
    defaults: { _controller: "VitrineBundle:Article:show" }
    methods:  GET
