client_index:
    path:     /
    defaults: { _controller: "VitrineBundle:Client:index" }
    methods:  GET

client_show:
    path:     show/{id}
    defaults: { _controller: "VitrineBundle:Client:show" }
    methods:  GET

client_new:
    path:     /new
    defaults: { _controller: "VitrineBundle:Client:new" }
    methods:  [GET, POST]

client_edit:
    path:     /edit/{id}
    defaults: { _controller: "VitrineBundle:Client:edit" }
    methods:  [GET, POST]

client_delete:
    path:     delete/{id}
    defaults: { _controller: "VitrineBundle:Client:delete" }
    methods:  DELETE
